"""added all

Revision ID: 71d00523c5f6
Revises: 
Create Date: 2023-10-02 23:16:30.533813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71d00523c5f6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('game',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.Column('number_of_moves', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('game_id')
    )
    op.create_table('game_score',
    sa.Column('score_id', sa.Integer(), nullable=False),
    sa.Column('vk_id', sa.Integer(), nullable=True),
    sa.Column('total_score', sa.Integer(), nullable=True),
    sa.Column('total_games', sa.Integer(), nullable=True),
    sa.Column('total_win', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('score_id')
    )
    op.create_table('stock',
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('game_stock_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['game_stock_id'], ['game.game_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('stock_id')
    )
    op.create_table('user',
    sa.Column('vk_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('stock_one', sa.Integer(), nullable=True),
    sa.Column('stock_two', sa.Integer(), nullable=True),
    sa.Column('stock_three', sa.Integer(), nullable=True),
    sa.Column('stock_one_buy', sa.Integer(), nullable=True),
    sa.Column('stock_two_buy', sa.Integer(), nullable=True),
    sa.Column('stock_three_buy', sa.Integer(), nullable=True),
    sa.Column('stock_one_sell', sa.Integer(), nullable=True),
    sa.Column('stock_two_sell', sa.Integer(), nullable=True),
    sa.Column('stock_three_sell', sa.Integer(), nullable=True),
    sa.Column('game_user_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['game_user_id'], ['game.game_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('vk_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('stock')
    op.drop_table('game_score')
    op.drop_table('game')
    op.drop_table('admins')
    # ### end Alembic commands ###
